{{ if .Values.k8s_objects.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client-app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "client-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range pluck $.Values.global.env .Values.configmap.filename | first }}
  {{ . }}: |-
{{ $.Files.Get . | indent 4 }}
  {{- end }}
{{ end }}