{{ if .Values.k8s_objects.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "client-app.fullname" . }}
spec:
  minAvailable: {{ default 1 .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "client-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}