kind: Service
apiVersion: v1
metadata:
  name: {{ include "client-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "client-app.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "client-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with pluck $.Values.global.env .Values.service | first }}
  {{- if eq .type "NodePort" }}
  type: NodePort
  {{- end }}
  ports:
  - protocol: TCP
    {{- if (and (eq .type "NodePort") (not (empty .nodePort))) }}
    nodePort: {{ .nodePort }}
    {{- end }}
    port: {{ default 80 .port }}
    targetPort: {{ default 80 .targetPort }}
  {{- end }}
